DROP TABLE IF EXISTS books_genres;

DROP TABLE IF EXISTS genres;

DROP TABLE IF EXISTS books;

CREATE TABLE IF NOT EXISTS books (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title VARCHAR (255) NOT NULL,
  author VARCHAR (255) NOT NULL,
  description TEXT,
  pages INTEGER NOT NULL,
  published_date DATE NOT NULL,
  isbn VARCHAR(20) UNIQUE,
  cover_filename VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS genres (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS books_genres (
  book_id INTEGER NOT NULL REFERENCES books (id) ON DELETE CASCADE,
  genre_id INTEGER NOT NULL REFERENCES genres (id) ON DELETE CASCADE,
  PRIMARY KEY (book_id, genre_id)
);